# Conversation States
(
    WAITING_INPUT_API_URL,
    WAITING_INPUT_API_KEY,
    WAITING_INPUT_MODEL_NAME,
    WAITING_INPUT_SYSTEM_PROMPT,
    WAITING_INPUT_WHITELIST_ADD,
    WAITING_INPUT_WHITELIST_REMOVE,
    # Wizard 状态
    WIZARD_INPUT_URL,
    WIZARD_INPUT_KEY,
    WIZARD_INPUT_MODEL,
    WIZARD_INPUT_TIMEZONE,
    # 搜索
    WAITING_INPUT_MODEL_SEARCH,
    # 聚合
    WAITING_INPUT_AGGREGATION_LATENCY,
    # 摘要模型
    WAITING_INPUT_SUMMARY_MODEL,
    WIZARD_INPUT_SUMMARY_MODEL,
    # Token 上限
    WAITING_INPUT_HISTORY_TOKENS,
    # 温度参数
    WAITING_INPUT_TEMPERATURE,
    # Agentic Management
    WAITING_INPUT_SUB_ADD,
    WAITING_INPUT_ACTIVE_HOURS,
    WAITING_INPUT_IDLE_THRESHOLD,
    # 语音配置
    WAITING_INPUT_TTS_URL,
    WAITING_INPUT_TTS_REF_AUDIO,
    WAITING_INPUT_TTS_REF_TEXT,
    WAITING_INPUT_TTS_LANG,
    WAITING_INPUT_TTS_SPEED
) = range(24)

