# Conversation States
(
    WAITING_INPUT_API_URL,
    WAITING_INPUT_API_KEY,
    WAITING_INPUT_MODEL_NAME,
    WAITING_INPUT_SYSTEM_PROMPT,
    WAITING_INPUT_WHITELIST_ADD,
    WAITING_INPUT_WHITELIST_REMOVE,
    # New Wizard States
    WIZARD_INPUT_URL,
    WIZARD_INPUT_KEY,
    WIZARD_INPUT_MODEL,
    WIZARD_INPUT_TIMEZONE,
    # Search
    WAITING_INPUT_MODEL_SEARCH
) = range(11)
